🔥 Sync 2024-07-05 18:39:18

diff --git a/luci-app-amlogic/root/usr/sbin/openwrt-backup b/luci-app-amlogic/root/usr/sbin/openwrt-backup
--- a/luci-app-amlogic/root/usr/sbin/openwrt-backup
+++ b/luci-app-amlogic/root/usr/sbin/openwrt-backup
@@ -11,7 +11,15 @@ SNAPSHOT_PRESTR=".snapshots/"
 BACKUP_DIR="/.reserved"
 BACKUP_NAME="openwrt_config.tar.gz"
 BACKUP_FILE="${BACKUP_DIR}/${BACKUP_NAME}"
-BACKUP_LIST='./etc/AdGuardHome.yaml \
+# Customize backup list
+backup_list_conf="/etc/amlogic_backup_list.conf"
+if [[ -s "${backup_list_conf}" ]]; then
+    while IFS= read -r line; do
+        BACKUP_LIST+="${line} "
+    done <"${backup_list_conf}"
+else
+    BACKUP_LIST='./etc/AdGuardHome.yaml \
+./etc/amlogic_backup_list.conf \
 ./etc/adblocklist/ \
 ./etc/amule/ \
 ./etc/balance_irq \
@@ -73,6 +81,7 @@ BACKUP_LIST='./etc/AdGuardHome.yaml \
 ./etc/v2raya/ \
 ./etc/verysync/ \
 ./root/.ssh/'
+fi
 
 if dmesg | grep 'meson' >/dev/null 2>&1; then
     PLATFORM="amlogic"
@@ -82,11 +91,12 @@ elif dmesg | grep 'sun50i-h6' >/dev/null 2>&1; then
     PLATFORM="allwinner"
 else
     source /etc/flippy-openwrt-release
-    case $PLATFORM in 
-        amlogic|rockchip|allwinner|qemu-aarch64) : ;;
-	*) echo "Unknown platform, only support amlogic or rockchip or allwinner h6 or qemu-aarch64!"
-           exit 1
-	   ;;
+    case $PLATFORM in
+    amlogic | rockchip | allwinner | qemu-aarch64) : ;;
+    *)
+        echo "Unknown platform, only support amlogic or rockchip or allwinner h6 or qemu-aarch64!"
+        exit 1
+        ;;
     esac
 fi
 
@@ -108,9 +118,12 @@ backup() {
 restore() {
     # Find the partition where root is located
     ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
-    if [ "${ROOT_PTNAME}" == "" ]; then
-        echo "Cannot find the partition corresponding to the root file system!"
-        exit 1
+    if [[ -z "${ROOT_PTNAME}" ]]; then
+        ROOT_PTNAME="$(df /overlay | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')"
+        if [[ -z "${ROOT_PTNAME}" ]]; then
+            echo "Cannot find the partition corresponding to the root file system!"
+            exit 1
+        fi
     fi
 
     # Find the disk where the partition is located, only supports mmcblk?p? sd?? hd?? vd?? and other formats
@@ -154,9 +167,12 @@ restore() {
 gen_fstab() {
     # Find the partition where root is located
     ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
-    if [ "${ROOT_PTNAME}" == "" ]; then
-        echo "Cannot find the partition corresponding to the root file system!"
-        exit 1
+    if [[ -z "${ROOT_PTNAME}" ]]; then
+        ROOT_PTNAME="$(df /overlay | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')"
+        if [[ -z "${ROOT_PTNAME}" ]]; then
+            echo "Cannot find the partition corresponding to the root file system!"
+            exit 1
+        fi
     fi
 
     # Find the disk where the partition is located, only supports mmcblk?p? sd?? hd?? vd?? and other formats
@@ -176,9 +192,12 @@ gen_fstab() {
     esac
 
     ROOT_MSG=$(lsblk -l -o NAME,PATH,MOUNTPOINT,UUID,FSTYPE,LABEL | awk '$3 ~ /^\/$/ {print $0}')
-    if [ "$ROOT_MSG" == "" ]; then
-        echo "Get rootfs message failed!"
-        exit 1
+    if [[ -z "${ROOT_MSG}" ]]; then
+        ROOT_MSG=$(lsblk -l -o NAME,PATH,MOUNTPOINT,UUID,FSTYPE,LABEL | awk '$3 ~ /^\/overlay$/ {print $0}')
+        if [[ -z "${ROOT_MSG}" ]]; then
+            echo "Get rootfs message failed!"
+            exit 1
+        fi
     fi
 
     ROOT_NAME=$(echo $ROOT_MSG | awk '{print $1}')
@@ -231,7 +250,7 @@ EOF
 	option enabled '1'
 	option enabled_fsck '1'
 	option fstype '${BOOT_FSTYPE}'
-           
+
 EOF
     echo "/etc/config/fstab generated."
     echo "please reboot"
@@ -370,10 +389,13 @@ delete_snapshot() {
 
 migrate_snapshot() {
     cur_rootdev=$(lsblk -l -o NAME,MOUNTPOINT | awk '$2~/^\/$/ {print $1}')
-    if [ "${cur_rootdev}" == "" ]; then
-        echo "The disk device corresponding to the current rootfs cannot be found!"
-        read -p "Press [ enter ] to return." q
-        return
+    if [[ -z "${cur_rootdev}" ]]; then
+        cur_rootdev=$(lsblk -l -o NAME,MOUNTPOINT | awk '$2~/^\/overlay$/ {print $1}')
+        if [[ -z "${cur_rootdev}" ]]; then
+            echo "The disk device corresponding to the current rootfs cannot be found!"
+            read -p "Press [ enter ] to return." q
+            return
+        fi
     fi
     dev_pre=$(echo "${cur_rootdev}" | awk '{print substr($1, 1, length($1)-1);}')
     rootdev_idx=$(echo "${cur_rootdev}" | awk '{print substr($1, length($1),1);}')
@@ -533,7 +555,7 @@ menu() {
         │       q. quit                   │
         │                                 │
         └─────────────────────────────────┘
-	
+
 EOF
         echo -ne "please select: [ ]\b\b"
         read select
diff --git a/luci-app-amlogic/root/usr/sbin/openwrt-update-amlogic b/luci-app-amlogic/root/usr/sbin/openwrt-update-amlogic
--- a/luci-app-amlogic/root/usr/sbin/openwrt-update-amlogic
+++ b/luci-app-amlogic/root/usr/sbin/openwrt-update-amlogic
@@ -33,9 +33,12 @@ fi
 
 # Find the partition where root is located
 ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
-if [ "${ROOT_PTNAME}" == "" ]; then
-    echo "Cannot find the partition corresponding to the root file system!"
-    exit 1
+if [[ -z "${ROOT_PTNAME}" ]]; then
+    ROOT_PTNAME="$(df /overlay | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')"
+    if [[ -z "${ROOT_PTNAME}" ]]; then
+        echo "Cannot find the partition corresponding to the root file system!"
+        exit 1
+    fi
 fi
 
 # Find the disk where the partition is located, only supports mmcblk?p? sd?? hd?? vd?? and other formats
@@ -114,7 +117,7 @@ fi
 DEPENDS="lsblk uuidgen grep awk btrfs mkfs.fat mkfs.btrfs md5sum fatlabel"
 echo "Check the necessary dependencies..."
 for dep in ${DEPENDS}; do
-    WITCH=$(which ${dep})
+    WITCH=$(busybox which ${dep})
     if [ "${WITCH}" == "" ]; then
         echo "Dependent command: ${dep} does not exist, upgrade cannot be performed, only flash through U disk/TF card!"
         exit 1
@@ -151,11 +154,14 @@ esac
 
 # find root partition
 ROOT_PART_MSG=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | awk '$3~/^part$/ && $5 ~ /^\/$/ {print $0}')
+if [[ -z "${ROOT_PART_MSG}" ]]; then
+    ROOT_PART_MSG=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | awk '$3~/^part$/ && $5 ~ /^\/overlay$/ {print $0}')
+fi
 ROOT_NAME=$(echo ${ROOT_PART_MSG} | awk '{print $1}')
 ROOT_PATH=$(echo ${ROOT_PART_MSG} | awk '{print $2}')
 ROOT_UUID=$(echo ${ROOT_PART_MSG} | awk '{print $4}')
 
-case $ROOT_NAME in
+case ${ROOT_NAME} in
 ${EMMC_NAME}${PARTITION_NAME}2)
     NEW_ROOT_NAME="${EMMC_NAME}${PARTITION_NAME}3"
     NEW_ROOT_LABEL="${LB_PRE}ROOTFS2"
@@ -837,6 +843,7 @@ umount -f ${P1} ${P2} 2>/dev/null
 losetup -D 2>/dev/null
 rm -rf ${P1} ${P2} 2>/dev/null
 rm -f ${IMG_NAME} 2>/dev/null
+rm -f sha256sums 2>/dev/null
 sync
 wait
 
diff --git a/luci-app-amlogic/root/usr/sbin/openwrt-update-kvm b/luci-app-amlogic/root/usr/sbin/openwrt-update-kvm
--- a/luci-app-amlogic/root/usr/sbin/openwrt-update-kvm
+++ b/luci-app-amlogic/root/usr/sbin/openwrt-update-kvm
@@ -23,7 +23,7 @@ WORK_DIR="${4}"
 DEPENDS="lsblk uuidgen grep awk btrfs mkfs.fat mkfs.btrfs md5sum fatlabel jq"
 echo "Check the necessary dependencies..."
 for dep in ${DEPENDS}; do
-    WITCH=$(which ${dep})
+    WITCH=$(busybox which ${dep})
     if [ "${WITCH}" == "" ]; then
         echo "Dependent command: ${dep} does not exist, upgrade cannot be performed!"
         exit 1
@@ -49,9 +49,12 @@ fi
 # Find the partition where root is located
 # vda2 or vda3
 ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
-if [ "${ROOT_PTNAME}" == "" ]; then
-    echo "Cannot find the partition corresponding to the root file system!"
-    exit 1
+if [[ -z "${ROOT_PTNAME}" ]]; then
+    ROOT_PTNAME="$(df /overlay | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')"
+    if [[ -z "${ROOT_PTNAME}" ]]; then
+        echo "Cannot find the partition corresponding to the root file system!"
+        exit 1
+    fi
 fi
 
 # Find the disk where the partition is located, only supports sd?? hd?? vd??
@@ -69,28 +72,28 @@ esac
 
 function get_docker_root {
     local data_root
-    if [[ -f /etc/config/dockerd ]];then
-	data_root=$(uci get dockerd.globals.data_root)
+    if [[ -f /etc/config/dockerd ]]; then
+        data_root=$(uci get dockerd.globals.data_root)
     fi
     if [[ -z "${data_root}" ]] && [[ -f /etc/docker/daemon.json ]]; then
-	data_root=$(jq -r '."data-root"' /etc/docker/daemon.json)
+        data_root=$(jq -r '."data-root"' /etc/docker/daemon.json)
     fi
     echo "$data_root"
 }
 DOCKER_ROOT=$(get_docker_root)
 
-if [[ -z "${WORK_DIR}" ]];then
+if [[ -z "${WORK_DIR}" ]]; then
     WORK_DIR="/mnt/${DISK_NAME}${PART_PRESTR}4/"
 fi
-if [[ ! -d "${WORK_DIR}" ]];then
+if [[ ! -d "${WORK_DIR}" ]]; then
     echo "the work directory is not exists. [ ${WORK_DIR} ]"
     exit 1
 fi
 
 cd "${WORK_DIR}"
-if [[ -d "/tmp/upload" ]] && [[ -f "/tmp/upload/*img*" ]];then
-    mv -f /tmp/upload/*img* . 
-    if [[ $? -ne 0 ]];then
+if [[ -d "/tmp/upload" ]] && [[ -f "/tmp/upload/*img*" ]]; then
+    mv -f /tmp/upload/*img* .
+    if [[ $? -ne 0 ]]; then
         echo "move file failed."
         exit 1
     fi
@@ -160,17 +163,20 @@ else
     echo -ne "Whether to backup and restore the current config files? y/n [y]\b\b"
     read yn
     case $yn in
-      n* | N*) BR_FLAG=0;;
+    n* | N*) BR_FLAG=0 ;;
     esac
 fi
 
 # find root partition
 ROOT_PART_MSG=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | awk '$3~/^part$/ && $5 ~ /^\/$/ {print $0}')
-ROOT_NAME=$(echo $ROOT_PART_MSG | awk '{print $1}')
-ROOT_DEV=$(echo $ROOT_PART_MSG | awk '{print $2}')
-ROOT_UUID=$(echo $ROOT_PART_MSG | awk '{print $4}')
+if [[ -z "${ROOT_PART_MSG}" ]]; then
+    ROOT_PART_MSG=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | awk '$3~/^part$/ && $5 ~ /^\/overlay$/ {print $0}')
+fi
+ROOT_NAME=$(echo ${ROOT_PART_MSG} | awk '{print $1}')
+ROOT_DEV=$(echo ${ROOT_PART_MSG} | awk '{print $2}')
+ROOT_UUID=$(echo ${ROOT_PART_MSG} | awk '{print $4}')
 
-case $ROOT_NAME in
+case ${ROOT_NAME} in
 ${DISK_NAME}${PART_PRESTR}2)
     NEW_ROOT_NAME="${DISK_NAME}${PART_PRESTR}3"
     NEW_ROOT_LABEL="${LABEL_PRESTR}ROOTFS2"
@@ -214,14 +220,14 @@ fi
 # fix loopdev issue in kernel 5.19
 function fix_loopdev() {
     local parentdev=${1##*/}
-    if [ ! -d /sys/block/${parentdev} ];then
+    if [ ! -d /sys/block/${parentdev} ]; then
         return
     fi
     subdevs=$(lsblk -l -o NAME | grep -E "^${parentdev}.+\$")
     for subdev in $subdevs; do
-        if [ ! -d /sys/block/${parentdev}/${subdev} ];then
+        if [ ! -d /sys/block/${parentdev}/${subdev} ]; then
             return
-        elif [ -b /dev/${sub_dev} ];then
+        elif [ -b /dev/${sub_dev} ]; then
             continue
         fi
         source /sys/block/${parentdev}/${subdev}/uevent
@@ -592,7 +598,7 @@ mv /tmp/grub.cfg.prev ./EFI/BOOT/
 
 echo "Modify efi configuration ... "
 cd /boot/efi/EFI/BOOT
-cat > grub.cfg <<EOF
+cat >grub.cfg <<EOF
 echo "search fs_uuid ${NEW_ROOT_UUID} ..."
 search.fs_uuid ${NEW_ROOT_UUID} root
 echo "root=\$root"
@@ -604,7 +610,7 @@ EOF
 
 echo "Modify boot configuration ... "
 cd ${NEW_ROOT_MOUNTPOINT}/boot/grub2
-cat > grub.cfg <<EOF
+cat >grub.cfg <<EOF
 insmod gzio
 insmod part_gpt
 insmod zstd
@@ -630,6 +636,7 @@ umount -f ${P1} ${P2} 2>/dev/null
 losetup -D 2>/dev/null
 rm -rf ${P1} ${P2} 2>/dev/null
 rm -f ${IMG_NAME} 2>/dev/null
+rm -f sha256sums 2>/dev/null
 sync
 wait
 
